name: stress-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - scikit-learn>=1.1.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - jupyterlab>=3.4.0
  - ipykernel>=6.15.0
  - plotly>=5.10.0
  - pip
  - pip:
    - ydata-profiling>=4.0.0
    - xgboost>=1.6.0
    - lightgbm>=3.3.0
    - imbalanced-learn>=0.9.0
    - yellowbrick>=1.5.0
    - tqdm>=4.64.0
    - python-dotenv>=0.20.0
    - pyyaml>=6.0
    - statsmodels>=0.13.0
